from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
import uuid


class GeneratedReport(models.Model):
    """생성된 리포트 기록"""

    REPORT_TYPE_CHOICES = [
        ('MOVE_IN', _('Move-in Report')),
        ('MOVE_OUT', _('Move-out Report')),
        ('COMPARISON', _('Before/After Comparison Report')),
    ]

    LANGUAGE_CHOICES = [
        ('ko', _('Korean')),
        ('en', _('English')),
        ('ja', _('Japanese')),
    ]

    STATUS_CHOICES = [
        ('PENDING', _('Pending')),
        ('GENERATING', _('Generating')),
        ('COMPLETED', _('Completed')),
        ('FAILED', _('Failed')),
    ]

    # 고유 식별자
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
        verbose_name=_('UUID')
    )

    # 계약 연결
    contract = models.ForeignKey(
        'contracts.Contract',
        on_delete=models.CASCADE,
        related_name='reports',
        verbose_name=_('Contract')
    )

    # 기록 연결 (개별 리포트의 경우)
    record = models.ForeignKey(
        'records.Record',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='reports',
        verbose_name=_('Record')
    )

    # 리포트 유형
    report_type = models.CharField(
        max_length=20,
        choices=REPORT_TYPE_CHOICES,
        verbose_name=_('Report Type')
    )

    # 언어
    language = models.CharField(
        max_length=5,
        choices=LANGUAGE_CHOICES,
        default='ko',
        verbose_name=_('Language')
    )

    # 상태
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='PENDING',
        verbose_name=_('Status')
    )

    # 생성된 파일
    file = models.FileField(
        upload_to='reports/%Y/%m/',
        null=True,
        blank=True,
        verbose_name=_('Report File')
    )

    # 생성자
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='generated_reports',
        verbose_name=_('Generated By')
    )

    # 에러 메시지 (실패 시)
    error_message = models.TextField(
        blank=True,
        verbose_name=_('Error Message')
    )

    # 타임스탬프
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created At')
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Updated At')
    )

    class Meta:
        verbose_name = _('Generated Report')
        verbose_name_plural = _('Generated Reports')
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.get_report_type_display()} - {self.contract.address} ({self.language})"

    def get_download_url(self):
        """다운로드 URL 반환"""
        if self.file:
            return self.file.url
        return None


class ReportShare(models.Model):
    """리포트 공유 링크"""

    # 고유 공유 토큰
    token = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
        verbose_name=_('Share Token')
    )

    # 리포트 연결
    report = models.ForeignKey(
        GeneratedReport,
        on_delete=models.CASCADE,
        related_name='shares',
        verbose_name=_('Report')
    )

    # 공유 설정
    expires_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_('Expires At'),
        help_text=_('Leave empty for no expiration')
    )
    max_downloads = models.PositiveIntegerField(
        null=True,
        blank=True,
        verbose_name=_('Max Downloads'),
        help_text=_('Leave empty for unlimited')
    )
    download_count = models.PositiveIntegerField(
        default=0,
        verbose_name=_('Download Count')
    )

    # 비밀번호 보호 (선택)
    password_hash = models.CharField(
        max_length=128,
        blank=True,
        verbose_name=_('Password Hash')
    )

    # 공유자
    shared_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='shared_reports',
        verbose_name=_('Shared By')
    )

    # 메모
    note = models.CharField(
        max_length=200,
        blank=True,
        verbose_name=_('Note'),
        help_text=_('Optional note for this share link')
    )

    # 활성화 상태
    is_active = models.BooleanField(
        default=True,
        verbose_name=_('Is Active')
    )

    # 타임스탬프
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created At')
    )

    class Meta:
        verbose_name = _('Report Share')
        verbose_name_plural = _('Report Shares')
        ordering = ['-created_at']

    def __str__(self):
        return f"Share: {self.report} ({self.token})"

    def is_valid(self):
        """공유 링크 유효성 확인"""
        from django.utils import timezone

        if not self.is_active:
            return False

        if self.expires_at and timezone.now() > self.expires_at:
            return False

        if self.max_downloads and self.download_count >= self.max_downloads:
            return False

        return True

    def increment_download(self):
        """다운로드 카운트 증가"""
        self.download_count += 1
        self.save(update_fields=['download_count'])
