# Generated by Django 4.2.26 on 2026-03-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name in Korean', max_length=200, verbose_name='Name (Korean)')),
                ('name_en', models.CharField(blank=True, help_text='Template name in English', max_length=200, verbose_name='Name (English)')),
                ('name_ja', models.CharField(blank=True, help_text='Template name in Japanese', max_length=200, verbose_name='Name (Japanese)')),
                ('country', models.CharField(choices=[('KR', 'Korea'), ('JP', 'Japan'), ('GLOBAL', 'Global')], default='KR', max_length=10, verbose_name='Country')),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('OFFICE', 'Office')], default='COMMERCIAL', max_length=20, verbose_name='Property Type')),
                ('description', models.TextField(blank=True, help_text='Description of the template purpose and usage', verbose_name='Description')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, help_text='Only active templates can be selected for new contracts', verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for the country/property type combination', verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Inspection Template',
                'verbose_name_plural': 'Inspection Templates',
                'ordering': ['country', 'property_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code within the template (e.g., ENTRANCE, LIVING_ROOM)', max_length=50, verbose_name='Code')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_ja', models.CharField(blank=True, max_length=100, verbose_name='Name (Japanese)')),
                ('description', models.TextField(blank=True, help_text='Additional guidance for this section', verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the template', verbose_name='Order')),
                ('is_required', models.BooleanField(default=True, help_text='Whether this section must have at least one item completed', verbose_name='Is Required')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='templates_engine.inspectiontemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Section',
                'verbose_name_plural': 'Template Sections',
                'ordering': ['template', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code within the section (e.g., FLOOR, WALL_EAST)', max_length=50, verbose_name='Code')),
                ('name_ko', models.CharField(max_length=100, verbose_name='Name (Korean)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Name (English)')),
                ('name_ja', models.CharField(blank=True, max_length=100, verbose_name='Name (Japanese)')),
                ('description_ko', models.TextField(blank=True, help_text='Guidance or instructions in Korean', verbose_name='Description (Korean)')),
                ('description_en', models.TextField(blank=True, help_text='Guidance or instructions in English', verbose_name='Description (English)')),
                ('description_ja', models.TextField(blank=True, help_text='Guidance or instructions in Japanese', verbose_name='Description (Japanese)')),
                ('item_type', models.CharField(choices=[('PHOTO', 'Photo'), ('CHECKBOX', 'Checkbox'), ('TEXT', 'Text Input'), ('SELECT', 'Select/Dropdown'), ('NUMBER', 'Number Input')], default='PHOTO', max_length=20, verbose_name='Item Type')),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for SELECT type items (list of {"value": "", "label_ko": "", "label_en": "", "label_ja": ""})', verbose_name='Options')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this item must be completed', verbose_name='Is Required')),
                ('min_photos', models.PositiveIntegerField(default=1, help_text='Minimum number of photos required (for PHOTO type)', verbose_name='Minimum Photos')),
                ('max_photos', models.PositiveIntegerField(default=10, help_text='Maximum number of photos allowed (for PHOTO type)', verbose_name='Maximum Photos')),
                ('responsibility_hint', models.CharField(choices=[('LANDLORD', 'Landlord Responsibility'), ('TENANT', 'Tenant Responsibility'), ('NEGOTIABLE', 'Negotiable')], default='NEGOTIABLE', help_text='Typical responsibility for restoration (informational only)', max_length=20, verbose_name='Responsibility Hint')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the section', verbose_name='Order')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='templates_engine.templatesection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Template Item',
                'verbose_name_plural': 'Template Items',
                'ordering': ['section', 'order', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectiontemplate',
            index=models.Index(fields=['country', 'property_type', 'is_active'], name='templates_e_country_802d09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatesection',
            unique_together={('template', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='templateitem',
            unique_together={('section', 'code')},
        ),
    ]
