# Generated by Django 4.2.26 on 2025-12-28 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('audio_file', models.FileField(upload_to='recordings/%Y/%m/', verbose_name='녹음 파일')),
                ('duration', models.IntegerField(default=0, verbose_name='녹음 시간(초)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='녹음 일시')),
                ('description', models.TextField(blank=True, verbose_name='메모')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='contracts.contract', verbose_name='연결된 계약')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '녹음 기록',
                'verbose_name_plural': '녹음 기록',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
