# Generated by Django 4.2.26 on 2025-12-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 일시'),
        ),
        migrations.AddField(
            model_name='recording',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('PROCESSING', '처리중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AddField(
            model_name='recording',
            name='summary',
            field=models.TextField(blank=True, help_text='AI가 생성한 요약문', verbose_name='요약'),
        ),
        migrations.AddField(
            model_name='recording',
            name='transcript',
            field=models.TextField(blank=True, help_text='음성을 텍스트로 변환한 원본 (관리자만 표시)', verbose_name='전사본'),
        ),
    ]
