# Generated by Django 4.2.26 on 2026-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_recording_processed_at_recording_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='제목 (영어)'),
        ),
        migrations.AddField(
            model_name='recording',
            name='title_ja',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='제목 (일본어)'),
        ),
    ]
