# Generated by Django 4.2.26 on 2026-04-28 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordings', '0003_add_translated_title_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='consent_rejected_reason',
            field=models.TextField(blank=True, verbose_name='동의 거절 사유'),
        ),
        migrations.AddField(
            model_name='recording',
            name='consent_status',
            field=models.CharField(choices=[('NOT_REQUIRED', '동의 불필요'), ('PENDING', '동의 대기'), ('APPROVED', '동의 완료'), ('REJECTED', '동의 거절')], default='NOT_REQUIRED', max_length=20, verbose_name='동의 상태'),
        ),
        migrations.AddField(
            model_name='recording',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='동의 일시'),
        ),
        migrations.AddField(
            model_name='recording',
            name='consented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consented_recordings', to=settings.AUTH_USER_MODEL, verbose_name='동의자'),
        ),
    ]
