# Generated by Django 4.2.26 on 2025-11-22 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_name', models.CharField(max_length=100, verbose_name='임대인 이름')),
                ('landlord_phone', models.CharField(max_length=20, verbose_name='임대인 연락처')),
                ('address', models.CharField(max_length=500, verbose_name='상가 주소')),
                ('contract_date', models.DateField(verbose_name='계약일')),
                ('move_in_date', models.DateField(verbose_name='입실일')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='퇴실 예정일')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='계약서 파일')),
                ('status', models.CharField(choices=[('ACTIVE', '진행중'), ('COMPLETED', '종료')], default='ACTIVE', max_length=10, verbose_name='계약 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landlord_contracts', to=settings.AUTH_USER_MODEL, verbose_name='임대인')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contracts', to=settings.AUTH_USER_MODEL, verbose_name='임차인')),
            ],
            options={
                'verbose_name': '계약',
                'verbose_name_plural': '계약들',
                'ordering': ['-created_at'],
            },
        ),
    ]
