# Generated by Django 4.2.26 on 2025-12-28 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_user_type', models.CharField(choices=[('TENANT', '임차인'), ('LANDLORD', '임대인')], max_length=10, verbose_name='초대받는 사람 유형')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='초대 토큰')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='수락 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('expires_at', models.DateTimeField(verbose_name='만료일시')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL, verbose_name='수락한 사람')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='contracts.contract', verbose_name='계약')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='초대한 사람')),
            ],
            options={
                'verbose_name': '계약 초대',
                'verbose_name_plural': '계약 초대들',
                'ordering': ['-created_at'],
            },
        ),
    ]
