# Generated by Django 4.2.26 on 2025-12-29 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_contractinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='임차인 이름'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='임차인 연락처'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='landlord_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='임대인 이름'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='landlord_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='임대인 연락처'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contracts', to=settings.AUTH_USER_MODEL, verbose_name='임차인'),
        ),
    ]
