# Generated by Django 4.2.26 on 2026-01-05 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_contract_tenant_name_contract_tenant_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATED', '계약 등록'), ('EXTENDED', '계약 연장'), ('TERMINATED', '계약 해지')], max_length=20, verbose_name='작업 유형')),
                ('previous_move_out_date', models.DateField(blank=True, null=True, verbose_name='이전 퇴실 예정일')),
                ('new_move_out_date', models.DateField(blank=True, null=True, verbose_name='새 퇴실 예정일')),
                ('extend_months', models.IntegerField(blank=True, null=True, verbose_name='연장 개월 수')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 일시')),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='실행자')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='contracts.contract', verbose_name='계약')),
            ],
            options={
                'verbose_name': '계약 이력',
                'verbose_name_plural': '계약 이력들',
                'ordering': ['-created_at'],
            },
        ),
    ]
