# Generated by Django 4.2.26 on 2026-01-05 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_contracthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('EXTEND', '계약 연장'), ('TERMINATE', '계약 해지')], max_length=20, verbose_name='요청 유형')),
                ('extend_months', models.IntegerField(blank=True, null=True, verbose_name='연장 개월 수')),
                ('status', models.CharField(choices=[('PENDING', '승인 대기'), ('APPROVED', '승인됨'), ('REJECTED', '거절됨')], default='PENDING', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='응답 일시')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='contracts.contract', verbose_name='계약')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_change_responses', to=settings.AUTH_USER_MODEL, verbose_name='응답자')),
            ],
            options={
                'verbose_name': '계약 변경 요청',
                'verbose_name_plural': '계약 변경 요청들',
                'ordering': ['-created_at'],
            },
        ),
    ]
