# Generated by Django 4.2.26 on 2026-01-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractchangerequest',
            name='response_note',
            field=models.TextField(blank=True, verbose_name='응답 메모 (승인/거절 사유)'),
        ),
    ]
