# Generated by Django 4.2.26 on 2026-01-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractchangerequest_response_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractchangerequest',
            name='is_read_by_requester',
            field=models.BooleanField(default=False, verbose_name='요청자 읽음 여부'),
        ),
    ]
