# Generated by Django 4.2.26 on 2026-02-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractchangerequest_is_read_by_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='blockchain_anchored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='블록체인 앵커링 시점'),
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_final_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='최종 해시'),
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='파일별 해시 메타데이터'),
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_status',
            field=models.CharField(choices=[('NONE', '미등록'), ('PENDING', '처리중'), ('ANCHORED', '등록됨'), ('FAILED', '실패')], default='NONE', max_length=10, verbose_name='블록체인 상태'),
        ),
        migrations.AddField(
            model_name='contract',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True, verbose_name='트랜잭션 해시'),
        ),
        migrations.AddField(
            model_name='contract',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계약 확정 시점'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='계약 확정 여부'),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='action_type',
            field=models.CharField(choices=[('CREATED', '계약 등록'), ('EXTENDED', '계약 연장'), ('TERMINATED', '계약 해지'), ('MODIFIED', '관리자 수정')], max_length=20, verbose_name='작업 유형'),
        ),
    ]
