# Generated by Django 4.2.26 on 2026-03-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_engine', '__first__'),
        ('contracts', '0008_add_blockchain_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='country',
            field=models.CharField(default='KR', help_text='Country code for this contract (KR, JP, etc.)', max_length=10, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Default inspection template for records in this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='templates_engine.inspectiontemplate', verbose_name='Inspection Template'),
        ),
    ]
