# Generated by Django 4.2.26 on 2026-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_country_contract_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='address_en',
            field=models.CharField(blank=True, help_text='영어 주소 (선택사항)', max_length=500, verbose_name='상가 주소 (영어)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='address_ja',
            field=models.CharField(blank=True, help_text='일본어 주소 (선택사항)', max_length=500, verbose_name='상가 주소 (일본어)'),
        ),
    ]
