# Generated by Django 4.2.26 on 2026-04-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_add_multilingual_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='address_ja',
        ),
    ]
