# Generated by Django 4.2.26 on 2026-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_remove_multilingual_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='address_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='주소 (영어)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='address_ja',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='주소 (일본어)'),
        ),
    ]
