# Generated by Django 4.2.26 on 2026-05-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_add_translated_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.CharField(max_length=500, verbose_name='주소'),
        ),
    ]
