# Generated by Django 4.2.26 on 2025-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('TENANT', '임차인'), ('LANDLORD', '임대인')], max_length=10, verbose_name='사용자 유형'),
        ),
    ]
