# Generated by Django 4.2.26 on 2025-11-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_account',
            field=models.CharField(blank=True, help_text='소셜 로그인 제공자 (예: google)', max_length=20, verbose_name='소셜 로그인'),
        ),
    ]
