"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mh*ce+pg$g(0w=+g=l!%^*97m5gxt^j_*cxgvl^%^&oah1118x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',  # Required for allauth
    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Custom apps
    'accounts',
    'contracts',
    'records',
    'recordings',
    'blockchain',
    # Core apps (Master Core)
    'core.templates_engine',
    'core.reports',
    'core.exports',
    # Country layers
    'countries.jp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # i18n - must be after SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Allauth middleware
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # i18n context processor
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'ko'

LANGUAGES = [
    ('ko', _('Korean')),
    ('en', _('English')),
    ('ja', _('Japanese')),
]

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Locale paths for translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Supported countries for the service
SUPPORTED_COUNTRIES = {
    'KR': {
        'name': 'Korea',
        'name_native': '대한민국',
        'languages': ['ko', 'en'],
        'default_language': 'ko',
        'timezone': 'Asia/Seoul',
        'currency': 'KRW',
        'property_types': ['RESIDENTIAL', 'COMMERCIAL'],
    },
    'JP': {
        'name': 'Japan',
        'name_native': '日本',
        'languages': ['ja', 'en'],
        'default_language': 'ja',
        'timezone': 'Asia/Tokyo',
        'currency': 'JPY',
        'property_types': ['RESIDENTIAL', 'COMMERCIAL', 'OFFICE'],
    },
}

# Default country for the service
DEFAULT_COUNTRY = 'KR'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploaded by users)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Login URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Django Sites Framework
SITE_ID = 1

# Django Allauth Settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth 설정
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 이메일 인증 비활성화
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # 사용자명 또는 이메일로 로그인
ACCOUNT_USERNAME_REQUIRED = False  # 소셜 로그인 시 자동 생성

# 소셜 로그인 설정
SOCIALACCOUNT_AUTO_SIGNUP = True  # 소셜 로그인 시 자동 가입
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # 소셜 이메일 검증 비활성화
SOCIALACCOUNT_QUERY_EMAIL = True  # 이메일 정보 요청
SOCIALACCOUNT_STORE_TOKENS = False  # 토큰 저장 불필요

# 소셜 로그인 어댑터
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.SocialAccountAdapter'

# Session Settings (세션 관리)
# 1시간(3600초) 동안 활동이 없으면 자동 로그아웃
SESSION_COOKIE_AGE = 3600  # 1시간 = 3600초

# 매 요청마다 세션 만료 시간을 갱신 (활동 감지)
# 사용자가 활동할 때마다 1시간이 리셋됨
SESSION_SAVE_EVERY_REQUEST = True

# 브라우저 종료 시 세션 만료 (재접속 시 자동 로그인 방지)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 세션 쿠키 보안 설정
SESSION_COOKIE_HTTPONLY = True  # JavaScript에서 쿠키 접근 불가 (XSS 방지)
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF 공격 방지


# OpenAI API Settings
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Klaytn 블록체인 설정 (직접 트랜잭션 방식)
# 테스트넷(Baobab): 1001, 메인넷: 8217
KLAYTN_CHAIN_ID = os.getenv('KLAYTN_CHAIN_ID', '1001')
# 지갑 개인키 (0x로 시작하는 64자리 hex)
KLAYTN_PRIVATE_KEY = os.getenv('KLAYTN_PRIVATE_KEY', '')
