# Generated by Django 4.2.26 on 2025-11-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('MOVE_IN', '입실'), ('MOVE_OUT', '퇴실')], max_length=10, verbose_name='기록 타입')),
                ('approval_status', models.CharField(choices=[('PENDING', '대기중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='PENDING', max_length=10, verbose_name='승인 상태')),
                ('landlord_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='임대인 승인 일시')),
                ('landlord_comment', models.TextField(blank=True, verbose_name='임대인 의견')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='contracts.contract', verbose_name='계약')),
            ],
            options={
                'verbose_name': '기록',
                'verbose_name_plural': '기록들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='이미지')),
                ('category', models.CharField(choices=[('WALL_EAST', '벽면 (동쪽)'), ('WALL_WEST', '벽면 (서쪽)'), ('WALL_SOUTH', '벽면 (남쪽)'), ('WALL_NORTH', '벽면 (북쪽)'), ('FLOOR', '바닥'), ('CEILING', '천장'), ('BATHROOM', '화장실'), ('KITCHEN', '주방/싱크대'), ('ELECTRICAL', '전기/설비'), ('SIGNBOARD', '간판 설치 부위'), ('DOOR', '출입문'), ('WINDOW', '창문'), ('OTHER', '기타')], max_length=20, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='촬영 일시')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('device_info', models.CharField(blank=True, max_length=200, verbose_name='촬영 기기 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='records.record', verbose_name='기록')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진들',
                'ordering': ['category', 'created_at'],
            },
        ),
    ]
