# Generated by Django 4.2.26 on 2026-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', '대기중'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='PENDING', max_length=10, verbose_name='승인 상태'),
        ),
        migrations.AddField(
            model_name='photo',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='반려 사유'),
        ),
    ]
