# Generated by Django 4.2.26 on 2026-02-21 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_approval_status_to_status(apps, schema_editor):
    """기존 approval_status 값을 새 status 필드로 마이그레이션"""
    Record = apps.get_model('records', 'Record')

    for record in Record.objects.all():
        old_status = record.approval_status
        if old_status == 'APPROVED':
            record.status = 'APPROVED'
        elif old_status == 'REJECTED':
            record.status = 'REJECTED'
        elif old_status == 'PENDING':
            # 사진이 있으면 SUBMITTED, 없으면 OPEN
            if record.photos.exists():
                record.status = 'SUBMITTED'
            else:
                record.status = 'OPEN'
        else:
            record.status = 'OPEN'
        record.save()


def reverse_migrate_status(apps, schema_editor):
    """역방향 마이그레이션: status를 approval_status로"""
    Record = apps.get_model('records', 'Record')

    for record in Record.objects.all():
        if record.status in ['APPROVED', 'REJECTED']:
            record.approval_status = record.status
        else:
            record.approval_status = 'PENDING'
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0002_photo_approval_status_photo_rejection_reason'),
    ]

    operations = [
        # 1. 새 필드들 추가
        migrations.AddField(
            model_name='record',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('REQUESTED', '요청됨'), ('OPEN', '업로드 가능'), ('SUBMITTED', '제출됨'), ('APPROVED', '승인됨'), ('REJECTED', '반려됨')], default='OPEN', max_length=10, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='record',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제출 일시'),
        ),
        migrations.AddField(
            model_name='record',
            name='upload_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='업로드 마감일'),
        ),
        # 2. 데이터 마이그레이션: approval_status -> status
        migrations.RunPython(migrate_approval_status_to_status, reverse_migrate_status),
        # 3. 기존 approval_status 필드 삭제
        migrations.RemoveField(
            model_name='record',
            name='approval_status',
        ),
    ]
