# Generated by Django 4.2.26 on 2026-03-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_engine', '__first__'),
        ('records', '0004_add_read_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='template_item',
            field=models.ForeignKey(blank=True, help_text='Associated template item. Null for legacy photos using category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='templates_engine.templateitem', verbose_name='Template Item'),
        ),
        migrations.AddField(
            model_name='record',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Selected inspection template for this record. Null for legacy records.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='templates_engine.inspectiontemplate', verbose_name='Inspection Template'),
        ),
    ]
