# Generated by Django 4.2.26 on 2026-05-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates_engine', '0001_initial'),
        ('records', '0005_photo_template_item_record_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_status', models.CharField(choices=[('NORMAL', '정상'), ('DEFECTIVE', '하자 있음'), ('AGED', '노후'), ('NEEDS_REPAIR', '수리 필요')], default='NORMAL', max_length=20, verbose_name='Condition Status')),
                ('response_value', models.TextField(blank=True, default='', verbose_name='Response Value')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_responses', to='records.record', verbose_name='Record')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='templates_engine.templateitem', verbose_name='Template Item')),
            ],
            options={
                'verbose_name': 'Record Item Response',
                'verbose_name_plural': 'Record Item Responses',
                'ordering': ['template_item__section__order', 'template_item__order'],
                'unique_together': {('record', 'template_item')},
            },
        ),
    ]
