# Generated by Django 4.2.26 on 2026-05-15 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_add_defect_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0006_add_record_item_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(help_text='e.g., Bathroom, Kitchen, Living Room', max_length=100, verbose_name='Location')),
                ('severity', models.CharField(choices=[('MINOR', '경미'), ('MAJOR', '중요'), ('CRITICAL', '긴급')], default='MINOR', max_length=10, verbose_name='Severity')),
                ('status', models.CharField(choices=[('REPORTED', '신고됨'), ('ACKNOWLEDGED', '확인됨'), ('IN_PROGRESS', '처리중'), ('RESOLVED', '해결됨')], default='REPORTED', max_length=20, verbose_name='Status')),
                ('landlord_response', models.TextField(blank=True, verbose_name='Landlord Response')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('is_read_by_landlord', models.BooleanField(default=False)),
                ('is_read_by_tenant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='contracts.contract', verbose_name='Contract')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reported By')),
            ],
            options={
                'verbose_name': 'Defect Report',
                'verbose_name_plural': 'Defect Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='defects/%Y/%m/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='records.defectreport', verbose_name='Defect Report')),
            ],
            options={
                'verbose_name': 'Defect Photo',
                'verbose_name_plural': 'Defect Photos',
                'ordering': ['created_at'],
            },
        ),
    ]
