# Generated by Django 4.2.26 on 2026-05-18 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_add_defect_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0008_add_repair_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('REPAIR', '수리비'), ('CLEANING', '청소비'), ('RESTORATION', '원상복구비'), ('OTHER', '기타')], default='REPAIR', max_length=20, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Amount')),
                ('paid_by', models.CharField(choices=[('TENANT', '임차인'), ('LANDLORD', '임대인')], default='LANDLORD', max_length=10, verbose_name='Paid By')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Receipt Image')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('is_read_by_landlord', models.BooleanField(default=False)),
                ('is_read_by_tenant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='contracts.contract', verbose_name='Contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('repair_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='records.repairrequest', verbose_name='Related Repair')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
    ]
