# Generated by Django 4.2.26 on 2026-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_add_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('MOVE_IN', '입실'), ('MOVE_OUT', '퇴실'), ('PRE_MOVE_OUT', '사전 점검')], max_length=20, verbose_name='기록 타입'),
        ),
    ]
