# Generated by Django 4.2.26 on 2026-04-02 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0009_contract_country_contract_template'),
        ('records', '0005_photo_template_item_record_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JapanRestorationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code for this restoration item', max_length=20, unique=True, verbose_name='Item Code')),
                ('category', models.CharField(choices=[('FLOOR', 'Floor'), ('WALL_CEILING', 'Wall/Ceiling'), ('DOOR_WINDOW', 'Door/Window'), ('EQUIPMENT', 'Equipment'), ('KITCHEN', 'Kitchen'), ('BATHROOM', 'Bathroom'), ('TOILET', 'Toilet'), ('OTHER', 'Other')], max_length=20, verbose_name='Category')),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('BOTH', 'Both')], default='BOTH', max_length=20, verbose_name='Property Type')),
                ('description_ja', models.TextField(help_text='Japanese description of the item', verbose_name='Description (Japanese)')),
                ('description_en', models.TextField(blank=True, help_text='English description of the item', verbose_name='Description (English)')),
                ('description_ko', models.TextField(blank=True, help_text='Korean description of the item', verbose_name='Description (Korean)')),
                ('responsibility', models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('NEGOTIABLE', 'Negotiable')], help_text='Who is responsible for restoration', max_length=20, verbose_name='Responsibility')),
                ('is_normal_wear', models.BooleanField(default=False, help_text='Is this considered normal wear and tear (通常損耗)?', verbose_name='Normal Wear and Tear')),
                ('cost_unit', models.CharField(blank=True, help_text='Unit for cost calculation (e.g., per sqm, per item)', max_length=50, verbose_name='Cost Unit')),
                ('typical_cost_range', models.CharField(blank=True, help_text='Typical cost range in JPY', max_length=100, verbose_name='Typical Cost Range')),
                ('depreciation_years', models.PositiveIntegerField(blank=True, help_text='Years for depreciation calculation', null=True, verbose_name='Depreciation Years')),
                ('depreciation_method', models.CharField(blank=True, help_text='Method used for depreciation (e.g., straight-line)', max_length=50, verbose_name='Depreciation Method')),
                ('guideline_reference', models.CharField(blank=True, help_text='Reference to MLIT guideline section', max_length=100, verbose_name='Guideline Reference')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Japan Restoration Item',
                'verbose_name_plural': 'Japan Restoration Items',
                'ordering': ['category', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PhotoRestorationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('NEGOTIABLE', 'Negotiable'), ('PENDING', 'Pending')], default='PENDING', max_length=20, verbose_name='Responsibility')),
                ('description', models.TextField(blank=True, help_text='Additional description of the damage/condition', verbose_name='Description')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=0, help_text='Estimated restoration cost in JPY', max_digits=10, null=True, verbose_name='Estimated Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restoration_tags', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_tags', to='records.photo', verbose_name='Photo')),
                ('restoration_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_tags', to='countries_jp.japanrestorationitem', verbose_name='Restoration Item')),
            ],
            options={
                'verbose_name': 'Photo Restoration Tag',
                'verbose_name_plural': 'Photo Restoration Tags',
            },
        ),
        migrations.CreateModel(
            name='ContractJapanExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('ORDINARY', 'Ordinary Lease'), ('FIXED_TERM', 'Fixed-term Lease')], default='ORDINARY', max_length=20, verbose_name='Contract Type')),
                ('renewal_type', models.CharField(choices=[('AUTO', 'Auto Renewal'), ('NEGOTIATED', 'Negotiated'), ('NONE', 'No Renewal')], default='AUTO', max_length=20, verbose_name='Renewal Type')),
                ('renewal_fee', models.DecimalField(blank=True, decimal_places=0, help_text='Renewal fee in JPY (更新料)', max_digits=12, null=True, verbose_name='Renewal Fee')),
                ('key_money', models.DecimalField(blank=True, decimal_places=0, help_text='Non-refundable key money in JPY (礼金)', max_digits=12, null=True, verbose_name='Key Money')),
                ('deposit', models.DecimalField(blank=True, decimal_places=0, help_text='Refundable security deposit in JPY (敷金)', max_digits=12, null=True, verbose_name='Security Deposit')),
                ('guarantee_fee', models.DecimalField(blank=True, decimal_places=0, help_text='Guarantee company fee in JPY (保証料)', max_digits=12, null=True, verbose_name='Guarantee Fee')),
                ('management_fee', models.DecimalField(blank=True, decimal_places=0, help_text='Monthly management fee in JPY (管理費・共益費)', max_digits=10, null=True, verbose_name='Management Fee')),
                ('restoration_clause', models.TextField(blank=True, help_text='Special restoration clause (原状回復特約)', verbose_name='Restoration Clause')),
                ('has_special_restoration_clause', models.BooleanField(default=False, help_text='Whether contract has special restoration terms', verbose_name='Has Special Restoration Clause')),
                ('agency_name', models.CharField(blank=True, help_text='Name of real estate agency (不動産会社)', max_length=200, verbose_name='Real Estate Agency')),
                ('agency_license', models.CharField(blank=True, help_text='Real estate license number (宅建業者免許番号)', max_length=100, verbose_name='Agency License Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='japan_extension', to='contracts.contract', verbose_name='Contract')),
            ],
            options={
                'verbose_name': 'Japan Contract Extension',
                'verbose_name_plural': 'Japan Contract Extensions',
            },
        ),
    ]
