# Generated by Django 4.2.26 on 2026-04-02 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Share Token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for no expiration', null=True, verbose_name='Expires At')),
                ('max_downloads', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited', null=True, verbose_name='Max Downloads')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download Count')),
                ('password_hash', models.CharField(blank=True, max_length=128, verbose_name='Password Hash')),
                ('note', models.CharField(blank=True, help_text='Optional note for this share link', max_length=200, verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.generatedreport', verbose_name='Report')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_reports', to=settings.AUTH_USER_MODEL, verbose_name='Shared By')),
            ],
            options={
                'verbose_name': 'Report Share',
                'verbose_name_plural': 'Report Shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
